---
title: "ATP Assay"
author: "Oscar and Brian"
date: "2022-09-12"
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
---

<style type="text/css">
.main-container {
  max-width: 2000px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r include = F}
## Packages
if(!any(rownames(installed.packages()) == "pacman")){
   install.packages("pacman")
}

pacman::p_load(here,
               tidyverse,
               multcomp,
               multcompView,
               DT,
               forcats,
               ggtext,
               pals,
               emmeans,
               kableExtra,
               broom,
               insight,
               ggpubr,
               stringr,
               DescTools,
               forcats)

## Load RData
load(here("rdata","ATP_tidy.rdata"))


```


```{r include= F}
## As Factor and reoder, and assign name rename
ATP.assay$Treatment <- factor(ATP.assay$Treatment, levels = c("no_treat", "AbO", "Chol", "Fru","LPS", "Chol_AbO","AbO_Fru", "AbO_LPS", "Chol_LPS", "Chol_Fru","Fru_LPS", "Chol_AbO_LPS","AbO_Fru_Chol_LPS"))

## New Dataframe reordered
ATP.assay_reorder <- ATP.assay[order(ATP.assay$Treatment), ]

## Assign Names to Levels
levels(ATP.assay_reorder$Treatment) <- list(Control  = "no_treat", 
                                                     AβO = "AbO",
                                                     Cholesterol = "Chol",
                                                     Fructose = "Fru",
                                                     LPS = "LPS",
                                                     AβO_Cholesterol = "Chol_AbO",
                                                     AβO_Fructose = "AbO_Fru",
                                                     AβO_LPS = "AbO_LPS",
                                                     Cholesterol_LPS = "Chol_LPS",
                                                     Fructose_Cholesterol = "Chol_Fru",
                                                     Fructose_LPS = "Fru_LPS",
                                                     AβO_Cholesterol_LPS = "Chol_AbO_LPS",
                                                     AβO_Fru_Chol_LPS = "AbO_Fru_Chol_LPS")

```

```{r include = F}
#Filter by sets
ATP.assay_reorder_1 <- ATP.assay_reorder %>%
        filter(Set %in% "1")

ATP.assay_reorder_2 <- ATP.assay_reorder %>%
        filter(Set %in% "2")

ATP.assay_reorder_3 <- ATP.assay_reorder %>%
        filter(Set %in% "3")
```


## ATP Content Experiment Combined {.tabset .tabset-fade .tabset-pills}


### Figure (non-normalize to protein)

```{r echo = F, warning = F, fig.height = 10, fig.width = 12}
# ANOVA
anova <- aov(`Calculated Fluorescence (nmol/well)` ~ Treatment, data = ATP.assay_reorder)

# Extract P-value
p_value <- signif(summary(anova)[[1]][["Pr(>F)"]][1],3)

# Contrast with Dunnett
emm_contrasts <- anova %>%
  emmeans("Treatment") %>%
  contrast("trt.vs.ctrl", infer = c(TRUE, TRUE)) %>%
  as_tibble() %>%
  mutate(p.value.round = insight::format_p(p.value, name = NULL,),
         p.value.star = insight::format_p(p.value, name = NULL, stars_only = TRUE)) 

emm_contrasts_split <- emm_contrasts
## Split string
emm_contrasts_split[c('group1', 'group2')] <- str_split_fixed(emm_contrasts_split$contrast, ' - ', 2) 




## Data Summary ##
dt_summary <- ATP.assay_reorder %>%
  group_by(Treatment) %>%
        summarize(mean = mean(`Calculated Fluorescence (nmol/well)`),
                  sd = sd(`Calculated Fluorescence (nmol/well)`))
#define custom color scale
myColors <- as.vector(kelly(13))
names(myColors) <- levels(dt_summary$Treatment)
custom_colors <- scale_fill_manual(name = "Treatment", values = myColors)

## Custom Factor where Control is First
dt_summary$Treatment <- factor(dt_summary$Treatment, 
                               levels = c("Control", 
                                          "LPS",
                                          "Fructose",
                                          "Fructose_LPS",
                                          "Cholesterol_LPS",
                                          "AβO",
                                          "AβO_LPS",
                                          "Fructose_Cholesterol",
                                          "Cholesterol",
                                          "AβO_Fructose",
                                          "AβO_Cholesterol",
                                          "AβO_Cholesterol_LPS",
                                          "AβO_Fru_Chol_LPS"))

################################## Create Plot ##################################
ATP_figure <- dt_summary %>%
ggplot() + 
        
        geom_bar(aes(y = mean, x = Treatment, fill = Treatment), stat = "identity", show.legend = TRUE) +
        
        geom_errorbar(data = dt_summary,
                aes(
                  ymin = mean - sd,
                  ymax = mean + sd,
                  x = Treatment
                ),
                width = 0.1) +
        
# Color Bar Plot (Discrete)
custom_colors + 
        
        labs(x = "Treatment", y = expression(paste("ATP, ","nmol/well")), subtitle = paste("ANOVA:", " P"," = ", paste0(p_value, collapse = NULL))) +
        
# letters
stat_pvalue_manual(data = emm_contrasts_split,
                   y.position = rep(2.8,12),
                   label = "p.value.star",
                   x = "group1",
                   vjust = 2,
                   remove.bracket=TRUE,
                   size = 10) +
        theme_classic() +
        theme(axis.text = element_text(angle = 90, color = "black"),
              text = element_text(size = 23)) +
        ylim(0,3)
ATP_figure
saveRDS(object = ATP_figure, file = here("manuscript","data","ATP.RDS"))
```


```{r include = F}
ggsave(plot = ATP_figure,here("manuscript","figures","ATP_assay.jpg"), dpi = 300, width = 10, height = 8)

```



### Stats - Dunnett's test (non-normalize to protein)

```{r echo = F}
datatable(as.data.frame(emm_contrasts), colnames = c("Contrast", "Mean Diff", "SE", "DF"," Lower CI 95%", "Upper CI 95%","T.ratio","P.adjusted","P.rounded","Sig Level"))

datatable(dt_summary, colnames = c("Treatment","Mean","Standard Deviation (SD)")) %>%
        formatRound(columns = c("mean","sd"), digits = 2)
```





## Normalized ATP Content Experiment Combined {.tabset .tabset-fade .tabset-pills}


### Figure (Normalize to protein)

```{r echo = F, warning = F, fig.height = 10, fig.width = 12}
# ANOVA
anova <- aov(norm_ATP ~ Treatment, data = ATP.assay_reorder)

# Extract P-value
p_value <- signif(summary(anova)[[1]][["Pr(>F)"]][1],3)

# Contrast with Dunnett
emm_contrasts <- anova %>%
  emmeans("Treatment") %>%
  contrast("trt.vs.ctrl", infer = c(TRUE, TRUE)) %>%
  as_tibble() %>%
  mutate(p.value.round = insight::format_p(p.value, name = NULL,),
         p.value.star = insight::format_p(p.value, name = NULL, stars_only = TRUE)) 

emm_contrasts_split <- emm_contrasts
## Split string
emm_contrasts_split[c('group1', 'group2')] <- str_split_fixed(emm_contrasts_split$contrast, ' - ', 2) 




## Data Summary ##
dt_summary <- ATP.assay_reorder %>%
  group_by(Treatment) %>%
        summarize(mean = mean(norm_ATP),
                  sd = sd(norm_ATP))

################################## Create Plot ##################################

ggplot() + 
        
        geom_bar(data = dt_summary,
    aes(y = mean, x = Treatment, fill = Treatment), stat = "identity", show.legend = FALSE) +
        
        geom_errorbar(data = dt_summary,
                aes(
                  ymin = mean - sd,
                  ymax = mean + sd,
                  x = Treatment
                ),
                width = 0.1) +
        
# Color Bar Plot (Discrete)
  scale_fill_manual(values=as.vector(kelly(20))) + 
        
        labs(x = "Treatment", y = expression(paste("Normalized ATP, ","nmol/ug/uL Protein")), subtitle = paste("ANOVA:", " P"," = ", paste0(p_value, collapse = NULL))) +
        
# letters
stat_pvalue_manual(data = emm_contrasts_split,
                   y.position = rep(2.8,12),
                   label = "p.value.star",
                   x = "group1",
                   vjust = 2,
                   remove.bracket=TRUE,
                   size = 10) +
        theme_classic() +
        theme(axis.text = element_text(angle = 90, color = "black"),
              text = element_text(size = 23)) 

```


```{r include = F}
 ggsave(here("figures","ATP_assay","Norm_ATP_dunnett.jpg"), dpi = 300, width = 10, height = 8)
```



### Stats - Dunnett's test (Normalize to protein)

```{r echo = F}
datatable(as.data.frame(emm_contrasts), colnames = c("Contrast", "Mean Diff", "SE", "DF"," Lower CI 95%", "Upper CI 95%","T.ratio","P.adjusted","P.rounded","Sig Level"))

datatable(dt_summary, colnames = c("Treatment","Mean","Standard Deviation (SD)")) %>%
        formatRound(columns = c("mean","sd"), digits = 2)
```
